const DELETE_THING = 'DELETE_THING';
const UPDATE_THING = 'UPDATE_THING';
const SET_THINGS = 'SET_THINGS';
const CREATE_THING = 'CREATE_THING';

export {
  DELETE_THING,
  UPDATE_THING,
  SET_THINGS,
  CREATE_THING
}