const DELETE_USER = 'DELETE_USER';
const SET_USERS = 'SET_USERS';
const CREATE_USER = 'CREATE_USER';
const UPDATE_USER = 'UPDATE_USER';

export {
  DELETE_USER, 
  SET_USERS,
  CREATE_USER,
  UPDATE_USER
}